onlyBuiltDependencies:
  - esbuild
  - oxc-resolver
  - rolldown
  - unrs-resolver
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@es-joy/jsdoccomment'
  - rolldown
  - '@oxc-project/types'
  - '@rolldown/pluginutils'
