/**
 * @author kazuya kawaguchi (a.k.a. kazupon)
 * @license MIT
 */

import TwoslashFloatingVue from '@shikijs/vitepress-twoslash/client'
import '@shikijs/vitepress-twoslash/style.css'
import DefaultTheme from 'vitepress/theme' // eslint-disable-line import/no-named-as-default -- NOTE(kazupon): vitepress/theme is a default export
import './style.css'
// eslint-disable-next-line import/no-unresolved -- NOTE(kazupon): This is a virtual module generated by vite-plugin-group-icons
import 'virtual:group-icons.css'
import type { EnhanceAppContext, Theme } from 'vitepress'

const theme: Theme = {
  ...DefaultTheme,
  enhanceApp({ app }: EnhanceAppContext) {
    app.use(TwoslashFloatingVue as never)
  }
}

export default theme
